src/Entity/Ships.php
<?php

namespace App\Entity;

use App\Repository\ShipsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ShipsRepository::class)]
class Ships
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column]
    private ?int $class = null;

    #[ORM\Column]
    private ?int $one_per_planet = null;

    #[ORM\Column]
    private ?int $level_max = null;

    #[ORM\Column]
    private ?int $cost_metal = null;

    #[ORM\Column]
    private ?int $cost_crystal = null;

    #[ORM\Column]
    private ?int $cost_deuterium = null;

    #[ORM\Column]
    private ?int $cost_dark_matter = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\Column]
    private ?int $consumption_deuterium = null;

    #[ORM\Column]
    private ?int $capacity = null;

    #[ORM\Column]
    private ?int $attack = null;

    #[ORM\Column]
    private ?int $defense = null;

    #[ORM\Column]
    private ?int $drive_science = null;

    /**
     * @var Collection<int, ShipDependencies>
     */
    #[ORM\OneToMany(targetEntity: ShipDependencies::class, mappedBy: 'ship')]
    private Collection $shipDependencies;

    private array $properties = [];

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image = null;

    public function __construct()
    {
        $this->shipDependencies = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getClass(): ?int
    {
        return $this->class;
    }

    public function setClass(int $class): static
    {
        $this->class = $class;

        return $this;
    }

    public function getOnePerPlanet(): ?int
    {
        return $this->one_per_planet;
    }

    public function setOnePerPlanet(int $one_per_planet): static
    {
        $this->one_per_planet = $one_per_planet;

        return $this;
    }

    public function getLevelMax(): ?int
    {
        return $this->level_max;
    }

    public function setLevelMax(int $level_max): static
    {
        $this->level_max = $level_max;

        return $this;
    }

    public function getCostMetal(): ?int
    {
        return $this->cost_metal;
    }

    public function setCostMetal(int $cost_metal): static
    {
        $this->cost_metal = $cost_metal;

        return $this;
    }

    public function getCostCrystal(): ?int
    {
        return $this->cost_crystal;
    }

    public function setCostCrystal(int $cost_crystal): static
    {
        $this->cost_crystal = $cost_crystal;

        return $this;
    }

    public function getCostDeuterium(): ?int
    {
        return $this->cost_deuterium;
    }

    public function setCostDeuterium(int $cost_deuterium): static
    {
        $this->cost_deuterium = $cost_deuterium;

        return $this;
    }

    public function getCostDarkMatter(): ?int
    {
        return $this->cost_dark_matter;
    }

    public function setCostDarkMatter(int $cost_dark_matter): static
    {
        $this->cost_dark_matter = $cost_dark_matter;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    public function getConsumptionDeuterium(): ?int
    {
        return $this->consumption_deuterium;
    }

    public function setConsumptionDeuterium(int $consumption_deuterium): static
    {
        $this->consumption_deuterium = $consumption_deuterium;

        return $this;
    }

    public function getCapacity(): ?int
    {
        return $this->capacity;
    }

    public function setCapacity(int $capacity): static
    {
        $this->capacity = $capacity;

        return $this;
    }

    public function getAttack(): ?int
    {
        return $this->attack;
    }

    public function setAttack(int $attack): static
    {
        $this->attack = $attack;

        return $this;
    }

    public function getDefense(): ?int
    {
        return $this->defense;
    }

    public function setDefense(int $defense): static
    {
        $this->defense = $defense;

        return $this;
    }

    public function getDriveScience(): ?int
    {
        return $this->drive_science;
    }

    public function setDriveScience(int $drive_science): static
    {
        $this->drive_science = $drive_science;

        return $this;
    }

    /**
     * @return Collection<int, ShipDependencies>
     */
    public function getShipDependencies(): Collection
    {
        return $this->shipDependencies;
    }

    public function addShipDependency(ShipDependencies $shipDependency): static
    {
        if (!$this->shipDependencies->contains($shipDependency)) {
            $this->shipDependencies->add($shipDependency);
            $shipDependency->setShip($this);
        }

        return $this;
    }

    public function removeShipDependency(ShipDependencies $shipDependency): static
    {
        if ($this->shipDependencies->removeElement($shipDependency)) {
            // set the owning side to null (unless already changed)
            if ($shipDependency->getShip() === $this) {
                $shipDependency->setShip(null);
            }
        }

        return $this;
    }

    public function __set($name, $value)
    {
        $this->properties[$name] = $value;
    }

    public function __get($name)
    {
        return $this->properties[$name] ?? null;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): static
    {
        $this->image = $image;

        return $this;
    }
}

src/Controller/ShipyardController.php
<?php

namespace App\Controller;

use App\Repository\PlanetBuildingRepository;
use App\Repository\PlanetRepository;
use App\Repository\ShipsRepository;
use App\Repository\UserScienceRepository;
use App\Service\BuildingCalculationService;
use App\Service\CheckMessagesService;
use App\Service\PlanetService;
use App\Service\ShipDependencyChecker;
use Doctrine\Persistence\ManagerRegistry;
use Psr\Log\LoggerInterface;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ShipyardController extends CustomAbstractController
{

    public function __construct(
        protected readonly PlanetRepository           $planetRepository,
        protected readonly BuildingCalculationService $buildingCalculationService,
        protected readonly CheckMessagesService       $checkMessagesService,
        protected readonly PlanetService              $planetService,
        protected readonly ManagerRegistry            $managerRegistry,
        protected readonly ShipsRepository            $shipsRepository,
        protected readonly ShipDependencyChecker      $shipDependencyChecker,
        protected readonly UserScienceRepository      $userScienceRepository,
        protected readonly PlanetBuildingRepository   $planetBuildingRepository,
        LoggerInterface                               $logger,
        Security                                      $security,
    ) {
        parent::__construct($security, $logger);
    }


    #[Route('/shipyard/{slug?}', name: 'shipyard')]
    public function index(
        $slug = NULL,
    ): Response {
        $this->denyAccessUnlessGranted('ROLE_USER');
        $planets    = $this->planetService->getPlanetsByPlayer($this->user, $slug);
        $planet     = $this->planetRepository->findOneBy(['user_uuid' => $this->user_uuid, 'slug' => $slug]);
        $actualPlanetId = $planets[1]->getId();

        $ships      = $this->shipsRepository->findAll();
        $i          = 0;

        $prodActual = $this->buildingCalculationService->calculateActualBuildingProduction(
            $this->planetBuildingRepository->findOneBy(['planet' => $actualPlanetId, 'building' => 1,],),
            $this->planetBuildingRepository->findOneBy(['planet' => $actualPlanetId, 'building' => 2,],),
            $this->planetBuildingRepository->findOneBy(['planet' => $actualPlanetId, 'building' => 3,],),
        );

        foreach($ships as $ship) {
            $ships[$i]->__set('isResearchable', $this->shipDependencyChecker->checkResearchable($ship, $planet));
            $this->shipsRepository->save($ship);
            $i++;
        }

        return $this->render(
            'shipyard/index.html.twig', [
            'planets'        => $planets[0],
            'selectedPlanet' => $planets[1],
            'planetData'     => $planets[2],
            'user'           => $this->user,
            'messages'       => $this->checkMessagesService->checkMessages(),
            'slug'           => $slug,
            'production'     => $prodActual,
            'ships'          => $ships,
        ],
        );
    }
}

templates/shipyard/index.html.twig
{% extends 'base.html.twig' %}
{% trans_default_domain 'ships' %}
{% block stylesheets %}
    {{ parent() }}
    <link href="{{ asset('css/buildings.css') }}" rel="stylesheet"/>
{% endblock %}
{% block title %}Space-Tactics Main{% endblock %}
{% block body %}

    {% include 'parts/ingame_mainmenu.html.twig' %}
    <section id="content" class="main buildings-container">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-2 col-md-12">
                    {% if app.user is not null %}
                        {% include 'parts/sidebar.html.twig' %}
                    {% endif %}
                </div>
                <div class="col-lg-10 col-md-12">
                    <section>
                        <div class="row">
                            <div class="col-lg-7 col-md-12">
                                <div class="row">
                                    <div class="col-lg-6 mt-1">
                                        <h3>{{ user.username }}, hier lässt du riesige Flotten bauen! </h3>
                                    </div>
                                    <div class="col-lg-6">
                                        <select name="planet" class="form-control planet-switcher-select">
                                            {% for planet in planets %}

                                                <option
                                                    value="{{ planet.slug }}"
                                                    style="color: #000;"
                                                    {{ planet.slug == slug ? 'selected' : '' }}
                                                >
                                                    {{ planet.name }}
                                                    {{ planet.systemX }}:{{ planet.systemY }}:{{ planet.systemZ }}
                                                </option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="container-fluid mt-3">
                            <div class="buildings">

                                {% if  ships is not empty %}
                                    {% for ship in ships %}
                                        {% set isResearchable = ship.__get('isResearchable') %}
                                        {% if isResearchable == 'true' %}

                                            <div class="building">
                                                <div class="building-headline">
                                                    <span>{{ ship.name|trans }}</span>
                                                </div>
                                                <div class="building-content">
                                                    <div class="col-6 building-content-image">
                                                        <img
                                                            src="{{ ship.image|default(asset('build/science/dummy.jpg')) }}"
                                                            alt="Science image"/>
                                                    </div>
                                                    <div class="col-6 building-content-specs">
                                                        <div class="metal">{{ 'metal'|trans({},'resources') }}
                                                            : {{ ship.costMetal }}</div>
                                                        <div class="crystal">{{ 'crystal'|trans({},'resources') }}
                                                            : {{ ship.costCrystal }}</div>
                                                        <div class="deuterium">{{ 'deuterium'|trans({},'resources') }}
                                                            : {{ ship.costDeuterium }}</div>
                                                    </div>
                                                </div>
                                                <div class="col-12 building-button mt-1">
                                                    <button type="button"
                                                            class="btn btn-light">
                                                        {{ 'upgrade_to'|trans }}
                                                    </button>
                                                </div>
                                            </div>
                                        {% endif %}
                                    {% endfor %}
                                {% endif %}
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </div>
    </section>
    {% include 'parts/footer.html.twig' %}
{% endblock %}