src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use DateTimeInterface;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Doctrine\Common\Collections\ArrayCollection;

#[ORM\Entity(repositoryClass: UserRepository::class)]
##[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = NULL;

    #[ORM\Column(length: 255)]
    private ?string $uuid = NULL;

    #[ORM\Column(length: 75)]
    private ?string $username = NULL;

    #[ORM\Column(length: 125)]
    private ?string $email = NULL;

    #[ORM\Column(length: 255)]
    private ?string $password = NULL;

    #[ORM\Column(length: 5)]
    private ?string $locale = NULL;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $uni = NULL;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?DateTimeInterface $register_on = NULL;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: TRUE)]
    private ?DateTimeInterface $activate_on = NULL;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: TRUE)]
    private ?DateTimeInterface $referal_on = NULL;

    #[ORM\Column(nullable: TRUE)]
    private ?int $referal_by = NULL;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: TRUE)]
    private ?DateTimeInterface $last_active = NULL;

    #[ORM\Column(length: 255, nullable: true)]
    private ?array $roles = null;

    #[ORM\Column(type: Types::BOOLEAN)]
    private bool $isVerified = false;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?DateTimeInterface $login_on = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?DateTimeInterface $logout_on = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $alliance = null;

    /**
     * @var Collection<int, UserScience>
     */
    #[ORM\OneToMany(targetEntity: UserScience::class, mappedBy: 'user_id')]
    private Collection $userSciences;

    #[ORM\Column(type: Types::SMALLINT, nullable: true)]
    private ?int $vacation = null;

    public function __construct()
    {
        $this->userSciences = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUuid(): ?string
    {
        return $this->uuid;
    }

    public function setUuid(string $uuid): self
    {
        $this->uuid = $uuid;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getLocale(): ?string
    {
        return $this->locale;
    }

    public function setLocale(string $locale): self
    {
        $this->locale = $locale;

        return $this;
    }

    public function getUni(): ?int
    {
        return $this->uni;
    }

    public function setUni(int $uni): self
    {
        $this->uni = $uni;

        return $this;
    }

    public function getRegisterOn(): ?DateTimeInterface
    {
        return $this->register_on;
    }

    public function setRegisterOn(DateTimeInterface $register_on): self
    {
        $this->register_on = $register_on;

        return $this;
    }

    public function getActivateOn(): ?DateTimeInterface
    {
        return $this->activate_on;
    }

    public function setActivateOn(?DateTimeInterface $activate_on): self
    {
        $this->activate_on = $activate_on;

        return $this;
    }

    public function getReferalOn(): ?DateTimeInterface
    {
        return $this->referal_on;
    }

    public function setReferalOn(?DateTimeInterface $referal_on): self
    {
        $this->referal_on = $referal_on;

        return $this;
    }

    public function getReferalBy(): ?int
    {
        return $this->referal_by;
    }

    public function setReferalBy(?int $referal_by): self
    {
        $this->referal_by = $referal_by;

        return $this;
    }

    public function getLastActive(): ?DateTimeInterface
    {
        return $this->last_active;
    }

    public function setLastActive(?DateTimeInterface $last_active): self
    {
        $this->last_active = $last_active;

        return $this;
    }

    public function getIsVerified(): ?int
    {
        return $this->is_verified;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(?int $is_verified): self
    {
        $this->is_verified = $is_verified;

        return $this;
    }

    public function getRoles(): array
    {
        return $this->roles;
    }

    public function setRoles(?array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /** @see \Serializable::serialize() */
    public function serialize()
    {
        return serialize(
            [
                $this->id,
                $this->username,
                $this->password,
                // see section on salt below
                // $this->salt,
            ],
        );
    }

    /** @see \Serializable::unserialize() */
    public function unserialize($serialized)
    {
        [
            $this->id,
            $this->username,
            $this->password,
            // see section on salt below
            // $this->salt
        ] = unserialize($serialized, ['allowed_classes' => false]);
    }

    public function getUserIdentifier(): string
    {
        return $this->email;
    }

    public function getLoginOn(): ?DateTimeInterface
    {
        return $this->login_on;
    }

    public function setLoginOn(?DateTimeInterface $login_on): static
    {
        $this->login_on = $login_on;

        return $this;
    }

    public function getLogoutOn(): ?DateTimeInterface
    {
        return $this->logout_on;
    }

    public function setLogoutOn(?DateTimeInterface $logout_on): static
    {
        $this->logout_on = $logout_on;

        return $this;
    }

    public function getAlliance(): ?string
    {
        return $this->alliance;
    }

    public function setAlliance(?string $alliance): void
    {
        $this->alliance = $alliance;
    }

    public function eraseCredentials(): void
    {
        // TODO: Implement eraseCredentials() method.
    }

    /**
     * @return Collection<int, UserScience>
     */
    public function getUserSciences(): Collection
    {
        return $this->userSciences;
    }

    public function addUserScience(UserScience $userScience): static
    {
        if (!$this->userSciences->contains($userScience)) {
            $this->userSciences->add($userScience);
            $userScience->setUserId($this);
        }

        return $this;
    }

    public function removeUserScience(UserScience $userScience): static
    {
        if ($this->userSciences->removeElement($userScience)) {
            // set the owning side to null (unless already changed)
            if ($userScience->getUserId() === $this) {
                $userScience->setUserId(null);
            }
        }

        return $this;
    }

    public function getVacation(): ?int
    {
        return $this->vacation;
    }

    public function setVacation(?int $vacation): static
    {
        $this->vacation = $vacation;

        return $this;
    }

}

src/Form/Type/UserType.php
<?php

namespace App\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;

class UserType extends AbstractType
{
    
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        
        $builder
            ->add('username', TextType::class, [
                'label'      => 'Benutzername',
                'label_attr' => [
                    'class' => 'col-1 col-form-label',
                    'for'   => 'username',
                ],
                'attr'       => [
                    'class'       => 'form-control',
                    'id'          => 'username',
                    'placeholder' => 'Benutzername',
                ],
                'required'   => TRUE,
            ])
            ->add('email', TextType::class, [
                'label'      => 'E-Mail',
                'label_attr' => [
                    'class' => 'col-1 col-form-label',
                    'for'   => 'email',
                ],
                'attr'       => [
                    'class'       => 'form-control',
                    'id'          => 'email',
                    'placeholder' => 'E-Mail',
                ],
                'required'   => TRUE,
            ])
            ->add('password', PasswordType::class, [
                'label'      => 'Passwort',
                'label_attr' => [
                    'class' => 'col-1 col-form-label',
                    'for'   => 'password',
                ],
                'attr'       => [
                    'class'       => 'form-control',
                    'id'          => 'password',
                    'placeholder' => 'Passwort',
                ],
                'required'   => TRUE,
            ])
            ->add('uni', ChoiceType::class, [
                'choices'    => [
                    'Universum 1' => 1,
                ],
                'label'      => 'Universum',
                'label_attr' => [
                    'class' => 'col-1 col-form-label',
                    'for'   => 'universe',
                ],
                'attr'       => [
                    'class'       => 'form-control',
                    'id'          => 'universe',
                    'placeholder' => 'Universum',
                ],
                'required'   => TRUE,
            ])
            ->add('locale', ChoiceType::class, [
                'choices'    => [
                    'Deutsch'  => 'de-DE',
                    'English'  => 'en-GB',
                    'Polski'   => 'pl_PL',
                    'Italiano' => 'it-IT',
                    'Français' => 'fr-FR',
                    'Türkçe'   => 'tr-TR',
                    'Русский'  => 'ru-RU',
                ],
                'label'      => 'Sprache',
                'label_attr' => [
                    'class' => 'col-1 col-form-label',
                    'for'   => 'sprache',
                ],
                'attr'       => [
                    'class'       => 'form-control',
                    'id'          => 'sprache',
                    'placeholder' => 'Sprache',
                ],
                'required'   => TRUE,
            ])
            ->add('submit', SubmitType::class, [
                'label' => 'Registrieren',
                'attr'  => [
                    'class' => 'btn btn-primary mt-3',
                ],
            ])
            ->getForm();
    }
    
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Form\Type\UserType;
use App\Repository\PlanetBuildingRepository;
use App\Repository\PlanetRepository;
use App\Repository\UserRepository;
use App\Service\BuildingCalculationService;
use App\Service\CheckMessagesService;
use App\Service\PlanetService;
use App\Service\UserService;
use Doctrine\Persistence\ManagerRegistry;
use Exception;
use Psr\Log\LoggerInterface;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;

class UserController extends CustomAbstractController
{
    public function __construct(
        protected readonly PlanetRepository           $planetRepository,
        protected readonly BuildingCalculationService $buildingCalculationService,
        protected readonly CheckMessagesService       $checkMessagesService,
        protected readonly PlanetService              $planetService,
        protected readonly ManagerRegistry            $managerRegistry,
        protected readonly PlanetBuildingRepository   $planetBuildingRepository,
        protected readonly UserRepository             $userRepository,
        protected readonly UserService                $userService,
        LoggerInterface                               $logger,
        Security                                      $security,
    ) {
        parent::__construct($security, $logger);
    }

    #[Route('account-settings', name: 'account_settings')]
    public function accountSettingsAction(
        ?Request $request,
        UserPasswordHasherInterface $passwordEncoder,
    ): Response
    {
        $user           = $this->getUserEntity();
        $planets        = $this->getPlanetsByUser($user);
        $actualPlanetId = $planets[1]->getId();
        $prodActual     = $this->calculateProduction($actualPlanetId);

        $alliance = $this->userService->getAllianceByUuid($user->getAlliance());
        $form     = $this->createForm(UserType::class, $user);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $data = $form->getData();


            #$this->userRepository->updatePassword($user, $passwordEncoder->hashPassword($user, $user->getPassword()));

            #return $this->redirectToRoute('account_settings');
        }

        return $this->render(
            'user/account_settings.html.twig',
            [
                'planets'        => $planets[0],
                'selectedPlanet' => $planets[1],
                'planetData'     => $planets[2],
                'messages'       => $this->checkMessagesService->checkMessages(),
                'slug'           => $user->getUuid(),
                'production'     => $prodActual,
                'user'           => $user,
                'alliance'       => $alliance ?? NULL,
                'userForm'       => $form,
            ],
        );
    }

    private function getUserEntity()
    {
        return $this->userRepository->findOneBy(['uuid' => $this->user->getUuid()]);
    }

    private function getPlanetsByUser($user): array
    {
        return $this->planetService->getPlanetsByPlayer($this->user, $user->getUuid());
    }

    private function calculateProduction($actualPlanetId): array
    {
        return $this->buildingCalculationService->calculateActualBuildingProduction(
            $this->planetBuildingRepository->findOneBy(['planet' => $actualPlanetId, 'building' => 1]),
            $this->planetBuildingRepository->findOneBy(['planet' => $actualPlanetId, 'building' => 2]),
            $this->planetBuildingRepository->findOneBy(['planet' => $actualPlanetId, 'building' => 3]),
        );
    }

    #[Route('update-user-status', name: 'update_user_status')]
    public function setVacation(
        Request $request,
    ): JsonResponse|Response {
        $this->isGranted('ROLE_USER');
        $vacationStatus       = (int)$request->get('status');
        $actualVacationStatus = $this->userRepository->findOneBy(['uuid' => $this->user->getUuid()])->getVacation();

        if($vacationStatus === $actualVacationStatus) {
            return $this->json(['status' => 'error', 'message' => 'Das geht so nicht.']);
        }

        try {
            $this->userRepository->updateVacationStatus($this->user->getUuid(), $vacationStatus);
            return $this->json(['status' => 'success', 'message' => 'Der Urlaubsstatus wurde erfolgreich geändert.']);
        }
        catch(Exception) {
            return $this->json(['status' => 'error', 'message' => 'Es ist ein Fehler aufgetreten.']);
        }
    }

    #[Route('update-password', name: 'update_password')]
    public function updatePasswordAction(
        Request $request,
        UserRepository $userRepository,
        UserPasswordHasherInterface $passwordEncoder,
    )
    {
        $user = $userRepository->findOneBy(['uuid' => $this->user->getUuid()]);
        if ($request->get('inputPasswordNew') !== $request->get('inputPasswordNewVerify')) {
            $this->addFlash('error', 'Die Passwörter stimmen nicht überein.');
            return $this->redirectToRoute('account_settings');
        }


        if(!$passwordEncoder->hashPassword($user, $request->get('inputPasswordOld'))){
            $this->addFlash('error', 'Das alte Passwort ist nicht korrekt.');
            return $this->redirectToRoute('account_settings');
        }

        $user->setPassword($passwordEncoder->hashPassword($user, $request->get('inputPasswordNew')));
        $userRepository->save($user, true);



        return $this->redirectToRoute('account_settings');
    }

}

templates/user/account_settings.html.twig
{% extends 'base.html.twig' %}

{% block title %}Space-Tactics Main{% endblock %}

{% block body %}
    <!-- Main Menu -->

    {% include 'parts/ingame_mainmenu.html.twig' %}

    <!-- Content -->
    <section id="content" class="main">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-2 col-md-12">
                    {% if app.user is not null %}
                        {% include 'parts/sidebar.html.twig' %}
                    {% endif %}
                </div>

                <div class="col-lg-10 col-md-12">
                    <section>
                        <div class="row">
                            <div class="col-lg-7 col-md-12">
                                <h3>Deine Accountdaten, {{ user.username }} </h3>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-lg-7 col-md-12">
                                <p>
                                    Du bist bei uns registriert seit:
                                    <strong>{{ user.registerOn|date('d.m.Y, H:i:m')~ ' Uhr' }}</strong><br/>
                                    Deine letzte Anmeldung war am:
                                    <strong>{{ user.lastActive|date('d.m.Y, H:i:m')~' Uhr'|default('noch nie') }}</strong><br/>
                                    Du bist in der Allianz: <strong>{{ alliance.name|default('keiner') }}</strong><br />

                                </p>
                            </div>


                            <div class="row">
                                <div class="col-6">
                                    <div class="alert alert-danger" id="errormessage"></div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-lg-5 col-md-12">
                                    <div class="form-check form-switch d-flex align-items-center">
                                        <input class="form-check-input me-3" type="checkbox" role="switch"
                                               id="flexSwitchCheckDefault" data-vac="{{ user.vacation }}">
                                        <label class="form-check-label" id="vacationLabel" for="flexSwitchCheckDefault">
                                            Urlaubsmodus off
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-12">
                            <span class="anchor" id="formChangePassword"></span>

                            <h3 class="mb-0">Passwort ändern</h3>
                            {% for error in app.flashes('error') %}
                                <div class="alert alert-danger" role="alert">
                                    {{ error }}
                                </div>
                            {% endfor %}
                            <form class="form" role="form" autocomplete="off" method="post" action="{{ path('update_password') }}">
                                <div class="form-group">
                                    <label for="inputPasswordOld">Aktuelles Passwort</label>
                                    <input type="password" class="form-control" id="inputPasswordOld" name="inputPasswordOld"
                                           required="">
                                </div>
                                <div class="form-group">
                                    <label for="inputPasswordNew">Neues Passwort</label>
                                    <input type="password" class="form-control" id="inputPasswordNew" name="inputPasswordNew"
                                           required="">
                                </div>
                                <div class="form-group">
                                    <label for="inputPasswordNewVerify">Neues Passwort bestätigen</label>
                                    <input type="password" class="form-control" id="inputPasswordNewVerify" name="inputPasswordNewVerify"
                                           required="">
                                </div>
                                <div class="form-group mt-3">
                                    <button type="submit" class="btn btn-success btn-lg float-right">Save
                                    </button>
                                </div>
                            </form>
                        </div>
                    </section>
                </div>

            </div>
        </div>
    </section>

    {% include 'parts/footer.html.twig' %}
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}
{% block body %}

    <!-- Main Menu -->
    {% include 'parts/mainmenu.html.twig' %}

    <!-- Content -->
    <section id="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-2 col-md-12">

                    <!-- Sidebar -->
                    {% include 'parts/sidebar.html.twig' %}


                </div>
                <div class="col-lg-10 col-md-12">

                    <!-- Main Content -->
                    <section>
                        <header>
                            <h2>Headline</h2>
                            <h3>Subline</h3>
                        </header>
                        <p>
                            Text
                        </p>
                    </section>
                </div>
            </div>
        </div>
    </section>

    <!-- Footer -->
    {% include 'parts/footer.html.twig' %}

    </div>

{% endblock %}